---
- hosts: localhost
  tasks:
    - name: transfer war
      synchronize:
        src: target/demo-0.0.1-SNAPSHOT.war
        dest: /home/tomcat
        mode: pull
      delegate_to: tomcatServer

- hosts: tomcatServer
  vars:
  - warRemotePath: /home/tomcat

  tasks:
  - name: get current date
    set_fact: bkpdate="{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

  - name: create directory with a date in name
    file: path="/home/tomcat/{{ bkpdate }}"
          state=directory
          mode=0755

  - name: backup war
    shell: "cp /usr/local/tomcat/webapps/{{ warName }} /home/tomcat/{{ bkpdate }}/"
    
  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest=/usr/local/tomcat/webapps/ROOT/ copy=no mode=0755 owner=tomcat9 group=tomcat9
    notify:
        - restart tomcat9
   
  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent
    
  - name: wait for tomcat to start
    wait_for: port=8080 timeout=60
    
  handlers:
    - name: Restart tomcat9
      service: name=tomcat9 state=restarted
